import { PlanItem } from './types';

export const englishSupervisorPlan: PlanItem[] = [
    // Page 1: Internal Operations
    {
        id: 101,
        domain: "العمليات الداخلية",
        objective: "تنفيذ خطط الإشراف التربوي",
        indicator: "تم تنفيذ 8 أنشطة للخطط والخلاصات",
        evidence: "الخطة لتنفيذ",
        activity: "المراجعة الدورية لانشطة الخطة",
        planned: 7,
        schedule: [1, 1, 1, 1, 1, 1, 1, null, null, null, null, null],
        executed: null,
        indicatorCount: 8,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: 102,
        domain: "العمليات الداخلية",
        objective: "تنفيذ خطط الإشراف التربوي",
        indicator: "تم تنفيذ 8 أنشطة للخطط والخلاصات",
        evidence: "نسخ التقارير",
        activity: "تسليم التقارير الكترونيا",
        planned: 7,
        schedule: [1, 1, 1, 1, 1, 1, 1, null, null, null, null, null],
        executed: null,
        indicatorCount: 8,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: 103,
        domain: "العمليات الداخلية",
        objective: "تنفيذ خطط الإشراف التربوي",
        indicator: "تم تنفيذ 8 أنشطة للخطط والخلاصات",
        evidence: "نسخ التقارير",
        activity: "إعداد الخلاصة الشهرية",
        planned: 7,
        schedule: [1, 1, 1, 1, 1, 1, 1, null, null, null, null, null],
        executed: null,
        indicatorCount: 8,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: 104,
        domain: "العمليات الداخلية",
        objective: "تنفيذ خطط الإشراف التربوي",
        indicator: "تم مناقشة ٢ تقارير أداء للخطط بنسبة ١٠٠%",
        evidence: "نسخة التقارير",
        activity: "تجهيز العرض الفصلي الداخلي",
        planned: 1,
        schedule: [null, null, null, null, 1, null, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 2,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: 105,
        domain: "العمليات الداخلية",
        objective: "تنفيذ خطط الإشراف التربوي",
        indicator: "تم مناقشة ٢ تقارير أداء للخطط بنسبة ١٠٠%",
        evidence: "نسخة التقارير",
        activity: "تجهيز العرض الختامي الداخلي",
        planned: 1,
        schedule: [null, null, null, null, null, null, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 2,
        weeklyExecution: [null, null, null, null]
    },
    // Page 2: Teaching
    {
        id: 106,
        domain: "التدريس",
        objective: "التخطيط التربوي للمنهج الدراسي",
        indicator: "تم تدريب المعلمين إعداد الخطط الفصلية لعدد 1 بنسبة 100%",
        evidence: "تقرير النشاط",
        activity: "دورة تدريبية في إعداد الخطط الفصلية",
        planned: 1,
        schedule: [1, null, null, null, null, null, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 1,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: 107,
        domain: "التدريس",
        objective: "التخطيط التربوي للمنهج الدراسي",
        indicator: "تم تقديم تغذية راجعة للخطط التدريسية للمواد الدراسية لعدد ٢ بنسبة 100%",
        evidence: "نسخ الخطط",
        activity: "ورش مراجعة الخطط",
        planned: 2,
        schedule: [1, 1, null, null, null, null, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 2,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: 108,
        domain: "التدريس",
        objective: "تفعيل استخدام طرائق التعلم النشط في العملية التعليمية",
        indicator: "تم ممارسة ٧٥% من المعلمين لاستراتيجيات التعلم النشط",
        evidence: "استمارة الزيارة الصفية",
        activity: "زيارات صفية",
        planned: 6,
        schedule: [1, 1, 1, 1, 1, 1, null, null, null, null, null, null],
        executed: null,
        indicatorCount: null,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: 109,
        domain: "التدريس",
        objective: "تفعيل استخدام طرائق التعلم النشط في العملية التعليمية",
        indicator: "تم ممارسة ٧٥% من المعلمين لاستراتيجيات التعلم النشط",
        evidence: "لقاء التوعية الأسبوعية",
        activity: "متبايعة المشرفين التربويين متابعة المعلمين التنويع من الاستراجيات",
        planned: 6,
        schedule: [1, 1, 1, 1, 1, 1, null, null, null, null, null, null],
        executed: null,
        indicatorCount: null,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: 110,
        domain: "التدريس",
        objective: "تفعيل استخدام طرائق التعلم النشط في العملية التعليمية",
        indicator: "تم ممارسة ٧٥% من المعلمين لاستراتيجيات التعلم النشط",
        evidence: "كشف بالاستراتيجيات حسب المراحل",
        activity: "متابعة تنوع الاستراجيات ميدانيا",
        planned: 6,
        schedule: [1, 1, 1, 1, 1, 1, null, null, null, null, null, null],
        executed: null,
        indicatorCount: null,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: 111,
        domain: "التدريس",
        objective: "تفعيل استخدام طرائق التعلم النشط في العملية التعليمية",
        indicator: "تم ممارسة ٧٥% من المعلمين لاستراتيجيات التعلم النشط",
        evidence: "جدول تنفيذ الدروس",
        activity: "دروس نموذجية بالاستراجيات",
        planned: 8,
        schedule: [null, null, 4, null, 4, null, null, null, null, null, null, null],
        executed: null,
        indicatorCount: null,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: 112,
        domain: "التدريس",
        objective: "تفعيل استخدام طرائق التعلم النشط في العملية التعليمية",
        indicator: "توظيف المعلمين للمهارات الحياتية المتضمن في المنهج",
        evidence: "جدول التنفيذ",
        activity: "زيارة تبادل خبرات",
        planned: 2,
        schedule: [1, null, null, 1, null, null, null, null, null, null, null, null],
        executed: null,
        indicatorCount: null,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: 113,
        domain: "التدريس",
        objective: "تفعيل استخدام طرائق التعلم النشط في العملية التعليمية",
        indicator: "توظيف المعلمين للمهارات الحياتية المتضمن في المنهج",
        evidence: "استمارت التحليل",
        activity: "تحليل تبادل الخرات",
        planned: 2,
        schedule: [null, 1, null, 1, null, null, null, null, null, null, null, null],
        executed: null,
        indicatorCount: null,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: 114,
        domain: "التدريس",
        objective: "تفعيل الإثراء الأمثل للمواد الدراسية",
        indicator: "تم تنفذ ٢ من البرامج العلاجية من قبل المعلم",
        evidence: "نسخة خطة المعلمين",
        activity: "زيارات صفية",
        planned: 2,
        schedule: [null, null, null, null, null, 1, null, 1, null, null, null, null],
        executed: null,
        indicatorCount: 2,
        weeklyExecution: [null, null, null, null]
    },
    // Page 3: Professional Development
    {
        id: 115,
        domain: "التنمية المهنية",
        objective: "تحديد برامج التنمية المهنية للكادر التربوي حسب طبيعة الوظيفة",
        indicator: "قياس أثر التدريب في الفئة المستفيدة لعدده أنشطة تدريبية بنسبة 70%",
        evidence: "تقرير قياس أثر التدريب",
        activity: "ورشة قياس الأثر أثناء الزيارات",
        planned: 5,
        schedule: [null, null, 2, 3, null, null, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 5,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: 116,
        domain: "التنمية المهنية",
        objective: "تحديد برامج التنمية المهنية للكادر التربوي حسب طبيعة الوظيفة",
        indicator: "تم تحديد برامج التنمية المهنية للمعلمين لعدد 4 بنسبة ٧٠%",
        evidence: "اللقاءات الأسبوعية",
        activity: "حصر أنشطة التنمية المهية حسب الاحتياج",
        planned: 6,
        schedule: [1, 1, 1, 1, 1, 1, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 4,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: 117,
        domain: "التنمية المهنية",
        objective: "تحديد برامج التنمية المهنية للكادر التربوي حسب طبيعة الوظيفة",
        indicator: "تم تحديد برامج التنمية المهنية للمعلمين لعدد 4 بنسبة ٧٠%",
        evidence: "اللقاءات الأسبوعية",
        activity: "إعداد جدول التنمية المهنية",
        planned: 6,
        schedule: [1, 1, 1, 1, 1, 1, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 4,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: 118,
        domain: "التنمية المهنية",
        objective: "تحديد برامج التنمية المهنية للكادر التربوي حسب طبيعة الوظيفة",
        indicator: "تم تحديد برامج التنمية المهنية للمعلمين لعدد 4 بنسبة ٧٠%",
        evidence: "نسخة التقرير",
        activity: "رفع تقريرر تنفيذ التنمية المهنية",
        planned: 6,
        schedule: [1, 1, 1, 1, 1, 1, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 4,
        weeklyExecution: [null, null, null, null]
    },
    // Page 4: Learning Resources
    {
        id: 119,
        domain: "وسائل ومصادر التعلم",
        objective: "تفعيل الاستخدام الأمثل لوسائل ومصادر التعلم",
        indicator: "تم تنفيذ عدد ٢ نشاط لتوعية المعلمين في استخدام الوسائل والمصادر",
        evidence: "المنشورات",
        activity: "منشور/مجموعات وتس/دورة ونلاين",
        planned: 8,
        schedule: [1, 1, 1, 1, 1, 1, 1, 1, null, null, null, null],
        executed: null,
        indicatorCount: 2,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: 120,
        domain: "وسائل ومصادر التعلم",
        objective: "تفعيل الاستخدام الأمثل لوسائل ومصادر التعلم",
        indicator: "استخدم المعلمون عدد 1 وسيلة لكل حصة بحسب طبيعة الدرس لعدد 6 أشهر بنسبة 80%",
        evidence: "سجلات المصادر",
        activity: "متابعة سجلات المصادر",
        planned: 6,
        schedule: [1, 1, 1, 1, 1, 1, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 6,
        weeklyExecution: [null, null, null, null]
    },
    // Page 5: Educational Achievement Assessment
    {
        id: 121,
        domain: "تقويم التحصيل العلمي",
        objective: "إعداد الاختبارات طبقا لجداول المواصفات",
        indicator: "أعد المعلمون عدد 4 اختبارات وفقاً لجدول المواصفات بنسبة كفاءة ٧٥%",
        evidence: "نماذج من المراجعة",
        activity: "ورشة تدريبية",
        planned: 2,
        schedule: [null, 1, null, null, null, null, null, null, null, null, null, 1],
        executed: null,
        indicatorCount: 4,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: 122,
        domain: "تقويم التحصيل العلمي",
        objective: "إعداد الاختبارات طبقا لجداول المواصفات",
        indicator: "أعد المعلمون عدد 4 اختبارات وفقاً لجدول المواصفات بنسبة كفاءة ٧٥%",
        evidence: "نماذج من المراجعة",
        activity: "ورشة مراجعة الاختبارات",
        planned: 6,
        schedule: [1, 1, 1, 1, 1, 1, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 4,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: 123,
        domain: "تقويم التحصيل العلمي",
        objective: "متابعة التقويم البنائي ومراجعته",
        indicator: "تم العمل بالتقويم البنائي عدد 4 في الفرع بنسبة (٨٠)",
        evidence: "تقرير الأداء",
        activity: "جلسات مراجعة",
        planned: 6,
        schedule: [1, 1, 1, 1, 1, 1, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 4,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: 124,
        domain: "تقويم التحصيل العلمي",
        objective: "تحليل نتائج الطلبة وفق منهجية علمية",
        indicator: "تم تحليل نتائج الاختبارات بطريقة علمية عدد ٤ بنسبة ١٠٠%",
        evidence: "نسخة التقرير",
        activity: "ورشة تحليل النتائج",
        planned: 3,
        schedule: [null, null, 1, 1, 1, null, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 4,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: 125,
        domain: "تقويم التحصيل العلمي",
        objective: "تنفيذ برامج المعالجة للطلبة (ضعاف التحصيل)",
        indicator: "تم تنفيذ برنامج ضعاف التحصيل العدد ٣ مراحل بنسبة 80%",
        evidence: "نسخة البرنامج",
        activity: "ورشة عمل لإعداد البرنامج",
        planned: 3,
        schedule: [1, 1, 1, null, null, null, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 3,
        weeklyExecution: [null, null, null, null]
    },
];
