import { PlanItem } from './types';

export const literarySupervisorPlan: PlanItem[] = [
    // Page 1: Internal Operations
    {
        id: '201',
        domain: "العمليات الداخلية",
        objective: "تنفيذ خطط الإشراف التربوي",
        indicator: "تم تنفيذ 8 أنشطة للخطط والخلاصات",
        evidence: "الخطة لتنفيذ",
        activity: "المراجعة الدورية لانشطة الخطة",
        planned: 7,
        schedule: [1, 1, 1, 1, 1, 1, 1, null, null, null, null, null],
        executed: null,
        indicatorCount: 8,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: '202',
        domain: "العمليات الداخلية",
        objective: "تنفيذ خطط الإشراف التربوي",
        indicator: "تم تنفيذ 8 أنشطة للخطط والخلاصات",
        evidence: "نسخ التقارير",
        activity: "تسليم التقارير الكترونيا",
        planned: 7,
        schedule: [1, 1, 1, 1, 1, 1, 1, null, null, null, null, null],
        executed: null,
        indicatorCount: 8,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: '203',
        domain: "العمليات الداخلية",
        objective: "تنفيذ خطط الإشراف التربوي",
        indicator: "تم تنفيذ 8 أنشطة للخطط والخلاصات",
        evidence: "نسخ التقارير",
        activity: "إعداد الخلاصة الشهرية",
        planned: 7,
        schedule: [1, 1, 1, 1, 1, 1, 1, null, null, null, null, null],
        executed: null,
        indicatorCount: 8,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: '204',
        domain: "العمليات الداخلية",
        objective: "تنفيذ خطط الإشراف التربوي",
        indicator: "تم مناقشة ٢ تقارير أداء للخطط بنسبة ١٠٠%",
        evidence: "نسخة التقارير",
        activity: "تجهيز العرض الفصلي الداخلي",
        planned: 1,
        schedule: [null, null, null, null, 1, null, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 2,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: '205',
        domain: "العمليات الداخلية",
        objective: "تنفيذ خطط الإشراف التربوي",
        indicator: "تم مناقشة ٢ تقارير أداء للخطط بنسبة ١٠٠%",
        evidence: "نسخة التقارير",
        activity: "تجهيز العرض الختامي الداخلي",
        planned: 1,
        schedule: [null, null, null, null, null, 1, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 2,
        weeklyExecution: [null, null, null, null]
    },
    // Page 2: Teaching
    {
        id: '206',
        domain: "التدريس",
        objective: "التخطيط التربوي للمنهج الدراسي",
        indicator: "تم تدريب المعلمين إعداد الخطط الفصلية لعدد 1 بنسبة 100%",
        evidence: "تقرير النشاط",
        activity: "دورة تدريبية في إعداد الخطط الفصلية",
        planned: 1,
        schedule: [1, null, null, null, null, null, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 1,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: '207',
        domain: "التدريس",
        objective: "التخطيط التربوي للمنهج الدراسي",
        indicator: "تم تقديم تغذية راجعة للخطط التدريسية للمواد الدراسية لعدد ٢ بنسبة 100%",
        evidence: "نسخ الخطط",
        activity: "ورش مراجعة الخطط",
        planned: 2,
        schedule: [1, 1, null, null, null, null, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 2,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: '208',
        domain: "التدريس",
        objective: "تفعيل استخدام طرائق التعلم النشط في العملية التعليمية",
        indicator: "تم ممارسة ٧٥% من المعلمين لاستراتيجيات التعلم النشط",
        evidence: "استمارة الزيارة الصفية",
        activity: "زيارات صفية",
        planned: 6,
        schedule: [1, 1, 1, 1, 1, 1, null, null, null, null, null, null],
        executed: null,
        indicatorCount: null,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: '209',
        domain: "التدريس",
        objective: "تفعيل استخدام طرائق التعلم النشط في العملية التعليمية",
        indicator: "تم ممارسة ٧٥% من المعلمين لاستراتيجيات التعلم النشط",
        evidence: "كشف بالاستراتيجيات",
        activity: "متابعة تنوع الاستراجيات ميدانيا",
        planned: 6,
        schedule: [1, 1, 1, 1, 1, 1, null, null, null, null, null, null],
        executed: null,
        indicatorCount: null,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: '210',
        domain: "التدريس",
        objective: "تفعيل استخدام طرائق التعلم النشط في العملية التعليمية",
        indicator: "تم ممارسة ٧٥% من المعلمين لاستراتيجيات التعلم النشط",
        evidence: "جدول تنفيذ الدروس",
        activity: "دروس نموذجية بالاستراجيات",
        planned: 8,
        schedule: [null, null, 4, 4, null, null, null, null, null, null, null, null],
        executed: null,
        indicatorCount: null,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: '211',
        domain: "التدريس",
        objective: "تفعيل استخدام طرائق التعلم النشط في العملية التعليمية",
        indicator: "توظيف المعلمين للمهارات الحياتية",
        evidence: "جدول التنفيذ",
        activity: "زيارة تبادل خبرات",
        planned: 2,
        schedule: [1, null, 1, null, null, null, null, null, null, null, null, null],
        executed: null,
        indicatorCount: null,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: '212',
        domain: "التدريس",
        objective: "تفعيل استخدام طرائق التعلم النشط في العملية التعليمية",
        indicator: "توظيف المعلمين للمهارات الحياتية",
        evidence: "استمارت التحليل",
        activity: "تحليل تبادل الخرات",
        planned: 2,
        schedule: [null, 1, null, 1, null, null, null, null, null, null, null, null],
        executed: null,
        indicatorCount: null,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: '213',
        domain: "التدريس",
        objective: "تفعيل الإثراء الأمثل للمواد الدراسية",
        indicator: "تم تنفذ ٢ من البرامج العلاجية من قبل المعلم",
        evidence: "نسخة خطة المعلمين",
        activity: "زيارات صفية",
        planned: 2,
        schedule: [null, null, null, null, null, 1, null, 1, null, null, null, null],
        executed: null,
        indicatorCount: 2,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: '214',
        domain: "البرامج النوعية",
        objective: "تفعيل الإثراء الأمثل للمواد الدراسية",
        indicator: "تم إضافة ٢ برامج نوعية للأساسي من ٤-١٢",
        evidence: "تصورات البرنامج",
        activity: "برنامج المهارات",
        planned: 1,
        schedule: [null, null, null, 1, null, null, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 2,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: '215',
        domain: "البرامج النوعية",
        objective: "تفعيل الإثراء الأمثل للمواد الدراسية",
        indicator: "تم إضافة ٢ برامج نوعية للأساسي من ٤-١٢",
        evidence: "سجلات المتابعة",
        activity: "متابعة تنفيذ البرنامج",
        planned: 3,
        schedule: [null, null, null, 1, 1, 1, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 2,
        weeklyExecution: [null, null, null, null]
    },
    // Page 3: Professional Development
    {
        id: '216',
        domain: "التنمية المهنية",
        objective: "تحديد برامج التنمية المهنية للكادر التربوي",
        indicator: "قياس أثر التدريب في الفئة المستفيدة",
        evidence: "تقرير قياس أثر التدريب",
        activity: "ورشة قياس الأثر أثناء الزيارات",
        planned: 5,
        schedule: [null, null, 2, 3, null, null, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 5,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: '217',
        domain: "التنمية المهنية",
        objective: "تحديد برامج التنمية المهنية للكادر التربوي",
        indicator: "تم تحديد برامج التنمية المهنية للمعلمين",
        evidence: "اللقاءات الأسبوعية",
        activity: "حصر أنشطة التنمية المهية حسب الاحتياج",
        planned: 6,
        schedule: [1, 1, 1, 1, 1, 1, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 4,
        weeklyExecution: [null, null, null, null]
    },
    // Page 4: Learning Resources
    {
        id: '218',
        domain: "وسائل ومصادر التعلم",
        objective: "تفعيل الاستخدام الأمثل لوسائل ومصادر التعلم",
        indicator: "تم تنفيذ عدد ٢ نشاط لتوعية المعلمين",
        evidence: "المنشورات",
        activity: "منشور/مجموعات وتس/دورة ونلاين",
        planned: 8,
        schedule: [1, 1, 1, 1, 1, 1, 1, 1, null, null, null, null],
        executed: null,
        indicatorCount: 2,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: '219',
        domain: "وسائل ومصادر التعلم",
        objective: "تفعيل الاستخدام الأمثل لوسائل ومصادر التعلم",
        indicator: "استخدم المعلمون عدد 1 وسيلة لكل حصة",
        evidence: "سجلات المصادر",
        activity: "متابعة سجلات المصادر",
        planned: 6,
        schedule: [1, 1, 1, 1, 1, 1, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 6,
        weeklyExecution: [null, null, null, null]
    },
    // Page 5: Educational Achievement Assessment
    {
        id: '220',
        domain: "تقويم التحصيل العلمي",
        objective: "إعداد الاختبارات طبقا لجداول المواصفات",
        indicator: "أعد المعلمون عدد 4 اختبارات",
        evidence: "نماذج من المراجعة",
        activity: "ورشة تدريبية",
        planned: 2,
        schedule: [null, 1, null, null, null, null, null, null, null, null, null, 1],
        executed: null,
        indicatorCount: 4,
        weeklyExecution: [null, null, null, null]
    },
    {
        id: '221',
        domain: "تقويم التحصيل العلمي",
        objective: "إعداد الاختبارات طبقا لجداول المواصفات",
        indicator: "أعد المعلمون عدد 4 اختبارات",
        evidence: "نماذج من المراجعة",
        activity: "ورشة مراجعة الاختبارات",
        planned: 6,
        schedule: [1, 1, 1, 1, 1, 1, null, null, null, null, null, null],
        executed: null,
        indicatorCount: 4,
        weeklyExecution: [null, null, null, null]
    },
];