import { PlanItem } from './types';

export const strategicPlanData: PlanItem[] = [
    { id: '110', domain: "الخطة الاستراتيجية", objective: "تطوير الإطار العام لتقويم الأداء المدرسي", indicator: "تم بناء وتطبيق إطار تقويم محدث بنسبة 100%", evidence: "نسخة من الإطار المعتمد، تقارير التطبيق التجريبي", activity: "ورشة عمل لتحديد محاور ومعايير الإطار الجديد", planned: 2, schedule: [null, 1, null, null, null, null, 1, null, null, null, null, null], executed: 0, indicatorCount: 1, weeklyExecution: [null, null, null, null] },
    { id: '111', domain: "الخطة الاستراتيجية", objective: "تطوير الإطار العام لتقويم الأداء المدرسي", indicator: "تم بناء وتطبيق إطار تقويم محدث بنسبة 100%", evidence: "نسخة من الإطار المعتمد، تقارير التطبيق التجريبي", activity: "تجريب الإطار في عينة من المدارس وجمع التغذية الراجعة", planned: 4, schedule: [null, null, null, 2, 2, null, null, null, null, null, null, null], executed: 0, indicatorCount: 1, weeklyExecution: [null, null, null, null] },
    { id: '112', domain: "الخطة الاستراتيجية", objective: "تطبيق التحول الرقمي في عمليات الإشراف التربوي", indicator: "تم أتمتة 3 عمليات إشرافية رئيسية (الزيارات الصفية، تقارير الأداء، متابعة الخطط) بنسبة 80%", evidence: "رابط المنصة الرقمية، دليل المستخدم", activity: "تدريب المشرفين والمعلمين على استخدام المنصة الرقمية", planned: 4, schedule: [1, 1, null, null, null, null, 1, 1, null, null, null, null], executed: 0, indicatorCount: 3, weeklyExecution: [null, null, null, null] },
    { id: '113', domain: "الخطة الاستراتيجية", objective: "تطبيق التحول الرقمي في عمليات الإشراف التربوي", indicator: "تم أتمتة 3 عمليات إشرافية رئيسية (الزيارات الصفية، تقارير الأداء، متابعة الخطط) بنسبة 80%", evidence: "رابط المنصة الرقمية، دليل المستخدم", activity: "متابعة تفعيل المنصة وتقديم الدعم الفني", planned: 8, schedule: [1, 1, 1, 1, 1, 1, 1, 1, null, null, null, null], executed: 0, indicatorCount: 3, weeklyExecution: [null, null, null, null] },
    { id: '114', domain: "الخطة الاستراتيجية", objective: "بناء مجتمعات تعلم مهنية فاعلة", indicator: "تم تشكيل وتفعيل 5 مجتمعات تعلم مهنية على مستوى المواد الدراسية بنسبة 100%", evidence: "محاضر اجتماعات المجتمعات، خطط عملها", activity: "لقاء تعريفي بأهمية مجتمعات التعلم المهنية وآليات عملها", planned: 1, schedule: [null, 1, null, null, null, null, null, null, null, null, null, null], executed: 0, indicatorCount: 5, weeklyExecution: [null, null, null, null] },
    { id: '115', domain: "الخطة الاستراتيجية", objective: "بناء مجتمعات تعلم مهنية فاعلة", indicator: "تم تشكيل وتفعيل 5 مجتمعات تعلم مهنية على مستوى المواد الدراسية بنسبة 100%", evidence: "محاضر اجتماعات المجتمعات، خطط عملها", activity: "متابعة اجتماعات المجتمعات وتقديم الدعم والتوجيه", planned: 6, schedule: [null, null, 1, 1, 1, null, 1, 1, 1, null, null, null], executed: 0, indicatorCount: 5, weeklyExecution: [null, null, null, null] }
];
